In [1]:
import re
import os
import requests
import wikipedia
import pandas as pd
from pyvalem.formula import Formula

In [2]:
filenames = os.listdir('/home/jingxin/data/exomolhr/loc_result/')
molecules = []
molhtmls = []
moltags = []
molnames = []
molmasses = []
isoslugs = [] 
isoformulas = []
isohtmls = []
isotags = []
isomasses = []
datasets = []
for file in filenames:
    piece = file.replace('.csv','').replace('_p','+').replace('_m','-').split('__')
    
    # Molecule
    molecule = piece[0]
    molecules.append(molecule)
    molhtmls.append(Formula(molecule).html)
    moltags.append(molecule.lower())
    molmasses.append(format(Formula(molecule).mass, '.6f'))
    # Search molecule names from NIST website and Wikipedia.
    r_search = requests.get('https://webbook.nist.gov/cgi/cbook.cgi?Formula='
                            +molecule.replace('+','%2B')+'&NoIon=on&Units=SI')
    title = r_search.text.split('<title>')[1].split('</title>')[0]
    if title != 'Search Results':
        molname = title
    else:
        link_list = re.findall(r"(?<=href=\").+?(?=\")", r_search.text)
        urls = []
        for url in link_list:
            if url.split('ID=')[0] == '/cgi/cbook.cgi?':
                urls.append(url)
        r_cgi = requests.get('https://webbook.nist.gov'+urls[0])
        molname = r_cgi.text.split('<title>')[1].split('</title>')[0]
    if molname == molecule:
        molname = wikipedia.page(molecule, auto_suggest=False).title
    molnames.append(molname.capitalize())
    
    # Isotopologue
    isotopologue = piece[1]
    isoformula = piece[3]
    isoslugs.append(isotopologue)
    isoformulas.append(isoformula)
    isohtmls.append(Formula(isoformula).html)
    isotags.append(isotopologue.replace('-','').lower())
    isomasses.append(format(Formula(isoformula).mass, '.6f'))
    
    # Dataset
    datasets.append(piece[2])
    
pieces_df = pd.DataFrame({'filename':filenames, 
                          'molecule':molecules, 'molhtml':molhtmls, 'moltag':moltags, 'molhtml':molhtmls, 'molname':molnames, 'molmass':molmasses,
                          'isoslug':isoslugs, 'isoformula':isoformulas, 'isohtml':isohtmls, 'isotag':isotags, 'isomass':isomasses, 
                          'dataset':datasets}).sort_values(by=['moltag','isotag','dataset'])
pieces_df['id'] = pieces_df.reset_index().index+1
pieces_colnames = ['id', 'filename', 'molecule', 'molhtml', 'moltag', 'molname', 'molmass',
                   'isoslug', 'isoformula', 'isohtml', 'isotag', 'isohtml', 'isomass', 'dataset']
pieces_df = pieces_df[pieces_colnames]
pieces_df

,id,filename,molecule,molhtml,moltag,molname,molmass,isoslug,isoformula,isohtml,isotag,isohtml,isomass,dataset
2,1,AlCl__27Al-35Cl__YNAT__(27Al)(35Cl).csv,AlCl,AlCl,alcl,Aluminum monochloride,62.431538,27Al-35Cl,(27Al)(35Cl),<sup>27</sup>Al<sup>35</sup>Cl,27al35cl,<sup>27</sup>Al<sup>35</sup>Cl,61.950391,YNAT
14,2,AlCl__27Al-37Cl__YNAT__(27Al)(37Cl).csv,AlCl,AlCl,alcl,Aluminum monochloride,62.431538,27Al-37Cl,(27Al)(37Cl),<sup>27</sup>Al<sup>37</sup>Cl,27al37cl,<sup>27</sup>Al<sup>37</sup>Cl,63.947441,YNAT
4,3,AlH__27Al-1H__AloHa__(27Al)(1H).csv,AlH,AlH,alh,Aluminum hydride,27.989538,27Al-1H,(27Al)(1H),<sup>27</sup>Al<sup>1</sup>H,27al1h,<sup>27</sup>Al<sup>1</sup>H,27.989363,AloHa
17,4,AlO__26Al-16O__ATP__(26Al)(16O).csv,AlO,AlO,alo,Aluminum monoxide,42.980538,26Al-16O,(26Al)(16O),<sup>26</sup>Al<sup>16</sup>O,26al16o,<sup>26</sup>Al<sup>16</sup>O,41.981806,ATP
13,5,AlO__27Al-16O__ATP__(27Al)(16O).csv,AlO,AlO,alo,Aluminum monoxide,42.980538,27Al-16O,(27Al)(16O),<sup>27</sup>Al<sup>16</sup>O,27al16o,<sup>27</sup>Al<sup>16</sup>O,42.976453,ATP
16,6,AlO__27Al-17O__ATP__(27Al)(17O).csv,AlO,AlO,alo,Aluminum monoxide,42.980538,27Al-17O,(27Al)(17O),<sup>27</sup>Al<sup>17</sup>O,27al17o,<sup>27</sup>Al<sup>17</sup>O,43.980670,ATP
18,7,AlO__27Al-18O__ATP__(27Al)(18O).csv,AlO,AlO,alo,Aluminum monoxide,42.980538,27Al-18O,(27Al)(18O),<sup>27</sup>Al<sup>18</sup>O,27al18o,<sup>27</sup>Al<sup>18</sup>O,44.980698,ATP
19,8,C2__12C2__8states__(12C)2.csv,C2,C<sub>2</sub>,c2,Dicarbon,24.022000,12C2,(12C)2,<sup>12</sup>C<sub>2</sub>,12c2,<sup>12</sup>C<sub>2</sub>,24.000000,8states
20,9,C2H2__12C2-1H2__aCeTY__(12C)2(1H)2.csv,C2H2,C<sub>2</sub>H<sub>2</sub>,c2h2,Acetylene,26.038000,12C2-1H2,(12C)2(1H)2,<sup>12</sup>C<sub>2</sub><sup>1</sup>H<sub>2<...,12c21h2,<sup>12</sup>C<sub>2</sub><sup>1</sup>H<sub>2<...,26.015650,aCeTY
9,10,CaH__40Ca-1H__XAB__(40Ca)(1H).csv,CaH,CaH,cah,Calcium monohydride,41.086000,40Ca-1H,(40Ca)(1H),<sup>40</sup>Ca<sup>1</sup>H,40ca1h,<sup>40</sup>Ca<sup>1</sup>H,40.970416,XAB
0,11,CN__12C-14N__Trihybrid__(12C)(14N).csv,CN,CN,cn,Cyano radical,26.018000,12C-14N,(12C)(14N),<sup>12</sup>C<sup>14</sup>N,12c14n,<sup>12</sup>C<sup>14</sup>N,26.003074,Trihybrid
41,12,CO2__12C-16O2__UCL-4000__(12C)(16O)2.csv,CO2,CO<sub>2</sub>,co2,Carbon dioxide,44.009000,12C-16O2,(12C)(16O)2,<sup>12</sup>C<sup>16</sup>O<sub>2</sub>,12c16o2,<sup>12</sup>C<sup>16</sup>O<sub>2</sub>,43.989829,UCL-4000
47,13,H2CO__1H2-12C-16O__AYTY__(1H)2(12C)(16O).csv,H2CO,H<sub>2</sub>CO,h2co,Formaldehyde,30.026000,1H2-12C-16O,(1H)2(12C)(16O),<sup>1</sup>H<sub>2</sub><sup>12</sup>C<sup>16...,1h212c16o,<sup>1</sup>H<sub>2</sub><sup>12</sup>C<sup>16...,30.010565,AYTY
35,14,H2O__1H2-16O__POKAZATEL__(1H)2(16O).csv,H2O,H<sub>2</sub>O,h2o,Water,18.015000,1H2-16O,(1H)2(16O),<sup>1</sup>H<sub>2</sub><sup>16</sup>O,1h216o,<sup>1</sup>H<sub>2</sub><sup>16</sup>O,18.010565,POKAZATEL
1,15,H2S__1H2-32S__AYT2__(1H)2(32S).csv,H2S,H<sub>2</sub>S,h2s,Hydrogen sulfide,34.076000,1H2-32S,(1H)2(32S),<sup>1</sup>H<sub>2</sub><sup>32</sup>S,1h232s,<sup>1</sup>H<sub>2</sub><sup>32</sup>S,33.987721,AYT2
40,16,H3_p__1H2-2H_p__ST__(1H)2(2H)+.csv,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000,1H2-2H+,(1H)2(2H)+,<sup>1</sup>H<sub>2</sub><sup>2</sup>H<sup>+</...,1h22h+,<sup>1</sup>H<sub>2</sub><sup>2</sup>H<sup>+</...,4.029752,ST
34,17,H3_p__1H3_p__MiZATeP__(1H)3+.csv,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000,1H3+,(1H)3+,<sup>1</sup>H<sub>3</sub><sup>+</sup>,1h3+,<sup>1</sup>H<sub>3</sub><sup>+</sup>,3.023475,MiZATeP
39,18,H3_p__2H2-1H_p__MiZo__(2H)2(1H)+.csv,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000,2H2-1H+,(2H)2(1H)+,<sup>2</sup>H<sub>2</sub><sup>1</sup>H<sup>+</...,2h21h+,<sup>2</sup>H<sub>2</sub><sup>1</sup>H<sup>+</...,5.036029,MiZo
15,19,H3_p__2H3_p__MiZo__(2H)3+.csv,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000,2H3+,(2H)3+,<sup>2</sup>H<sub>3</sub><sup>+</sup>,2h3+,<sup>2</sup>H<sub>3</sub><sup>+</sup>,6.042305,MiZo
36,20,H3O_p__1H3-16O_p__eXeL__(1H)3(16O)+.csv,H3O+,H<sub>3</sub>O<sup>+</sup>,h3o+,Hydronium cation,19.023000,1H3-16O+,(1H)3(16O)+,<sup>1</sup>H<sub>3</sub><sup>16</sup>O<sup>+<...,1h316o+,<sup>1</sup>H<sub>3</sub><sup>16</sup>O<sup>+<...,19.018390,eXeL
46,21,LiOH__6Li-16O-1H__OYT7__(6Li)(16O)(1H).csv,LiOH,LiOH,lioh,Lithium hydroxide,23.947000,6Li-16O-1H,(6Li)(16O)(1H),<sup>6</sup>Li<sup>16</sup>O<sup>1</sup>H,6li16o1h,<sup>6</sup>Li<sup>16</sup>O<sup>1</sup>H,23.017863,OYT7
33,22,LiOH__7Li-16O-1H__OYT7__(7Li)(16O)(1H).csv,LiOH,LiOH,lioh,Lithium hydroxide,23.947000,7Li-16O-1H,(7Li)(16O)(1H),<sup>7</sup>Li<sup>16</sup>O<sup>1</sup>H,7li16o1h,<sup>7</sup>Li<sup>16</sup>O<sup>1</sup>H,24.018743,OYT7
3,23,MgH__24Mg-1H__XAB__(24Mg)(1H).csv,MgH,MgH,mgh,Magnesium monohydride,25.313000,24Mg-1H,(24Mg)(1H),<sup>24</sup>Mg<sup>1</sup>H,24mg1h,<sup>24</sup>Mg<sup>1</sup>H,24.992867,XAB
5,24,MgH__25Mg-1H__XAB__(25Mg)(1H).csv,MgH,MgH,mgh,Magnesium monohydride,25.313000,25Mg-1H,(25Mg)(1H),<sup>25</sup>Mg<sup>1</sup>H,25mg1h,<sup>25</sup>Mg<sup>1</sup>H,25.993662,XAB
7,25,MgH__26Mg-1H__XAB__(26Mg)(1H).csv,MgH,MgH,mgh,Magnesium monohydride,25.313000,26Mg-1H,(26Mg)(1H),<sup>26</sup>Mg<sup>1</sup>H,26mg1h,<sup>26</sup>Mg<sup>1</sup>H,26.990418,XAB
6,26,NH__14N-1H__kNigHt__(14N)(1H).csv,NH,NH,nh,Imidogen,15.015000,14N-1H,(14N)(1H),<sup>14</sup>N<sup>1</sup>H,14n1h,<sup>14</sup>N<sup>1</sup>H,15.010899,kNigHt
11,27,NH__14N-2H__kNigHt__(14N)(2H).csv,NH,NH,nh,Imidogen,15.015000,14N-2H,(14N)(2H),<sup>14</sup>N<sup>2</sup>H,14n2h,<sup>14</sup>N<sup>2</sup>H,16.017176,kNigHt
8,28,NH__15N-1H__kNigHt__(15N)(1H).csv,NH,NH,nh,Imidogen,15.015000,15N-1H,(15N)(1H),<sup>15</sup>N<sup>1</sup>H,15n1h,<sup>15</sup>N<sup>1</sup>H,16.007934,kNigHt
10,29,NH__15N-2H__kNigHt__(15N)(2H).csv,NH,NH,nh,Imidogen,15.015000,15N-2H,(15N)(2H),<sup>15</sup>N<sup>2</sup>H,15n2h,<sup>15</sup>N<sup>2</sup>H,17.014211,kNigHt
38,30,NH3__14N-1H3__CoYuTe__(14N)(1H)3.csv,NH3,NH<sub>3</sub>,nh3,Ammonia,17.031000,14N-1H3,(14N)(1H)3,<sup>14</sup>N<sup>1</sup>H<sub>3</sub>,14n1h3,<sup>14</sup>N<sup>1</sup>H<sub>3</sub>,17.026549,CoYuTe
12,31,NO__14N-16O__XABC__(14N)(16O).csv,NO,NO,no,Nitric oxide,30.006000,14N-16O,(14N)(16O),<sup>14</sup>N<sup>16</sup>O,14n16o,<sup>14</sup>N<sup>16</sup>O,29.997989,XABC
21,32,SiN__28Si-14N__SiNfull__(28Si)(14N).csv,SiN,SiN,sin,Silicon nitride,42.092000,28Si-14N,(28Si)(14N),<sup>28</sup>Si<sup>14</sup>N,28si14n,<sup>28</sup>Si<sup>14</sup>N,41.980001,SiNfull
22,33,SiN__28Si-15N__SiNfull__(28Si)(15N).csv,SiN,SiN,sin,Silicon nitride,42.092000,28Si-15N,(28Si)(15N),<sup>28</sup>Si<sup>15</sup>N,28si15n,<sup>28</sup>Si<sup>15</sup>N,42.977035,SiNfull
23,34,SiN__29Si-14N__SiNfull__(29Si)(14N).csv,SiN,SiN,sin,Silicon nitride,42.092000,29Si-14N,(29Si)(14N),<sup>29</sup>Si<sup>14</sup>N,29si14n,<sup>29</sup>Si<sup>14</sup>N,42.979569,SiNfull
24,35,SiN__30Si-14N__SiNfull__(30Si)(14N).csv,SiN,SiN,sin,Silicon nitride,42.092000,30Si-14N,(30Si)(14N),<sup>30</sup>Si<sup>14</sup>N,30si14n,<sup>30</sup>Si<sup>14</sup>N,43.976844,SiNfull
32,36,SiO__28Si-16O__SiOUVenIR__(28Si)(16O).csv,SiO,SiO,sio,Silicon monoxide,44.084000,28Si-16O,(28Si)(16O),<sup>28</sup>Si<sup>16</sup>O,28si16o,<sup>28</sup>Si<sup>16</sup>O,43.971841,SiOUVenIR
42,37,SO__32S-16O__SOLIS__(32S)(16O).csv,SO,SO,so,Sulfur monoxide,48.059000,32S-16O,(32S)(16O),<sup>32</sup>S<sup>16</sup>O,32s16o,<sup>32</sup>S<sup>16</sup>O,47.966986,SOLIS
37,38,SO2__32S-16O2__ExoAmes__(32S)(16O)2.csv,SO2,SO<sub>2</sub>,so2,Sulfur dioxide,64.058000,32S-16O2,(32S)(16O)2,<sup>32</sup>S<sup>16</sup>O<sub>2</sub>,32s16o2,<sup>32</sup>S<sup>16</sup>O<sub>2</sub>,63.961900,ExoAmes
25,39,TiO__48Ti-16O__Toto__(48Ti)(16O).csv,TiO,TiO,tio,Titanium oxide,63.866000,48Ti-16O,(48Ti)(16O),<sup>48</sup>Ti<sup>16</sup>O,48ti16o,<sup>48</sup>Ti<sup>16</sup>O,63.942856,Toto
43,40,YO__89Y-16O__BRYTS__(89Y)(16O).csv,YO,YO,yo,Yttrium monoxide,104.904840,89Y-16O,(89Y)(16O),<sup>89</sup>Y<sup>16</sup>O,89y16o,<sup>89</sup>Y<sup>16</sup>O,104.900756,BRYTS
44,41,YO__89Y-17O__BRYTS__(89Y)(17O).csv,YO,YO,yo,Yttrium monoxide,104.904840,89Y-17O,(89Y)(17O),<sup>89</sup>Y<sup>17</sup>O,89y17o,<sup>89</sup>Y<sup>17</sup>O,105.904973,BRYTS
45,42,YO__89Y-18O__BRYTS__(89Y)(18O).csv,YO,YO,yo,Yttrium monoxide,104.904840,89Y-18O,(89Y)(18O),<sup>89</sup>Y<sup>18</sup>O,89y18o,<sup>89</sup>Y<sup>18</sup>O,106.905001,BRYTS
26,43,ZrO__90Zr-16O__ZorrO__(90Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,90Zr-16O,(90Zr)(16O),<sup>90</sup>Zr<sup>16</sup>O,90zr16o,<sup>90</sup>Zr<sup>16</sup>O,105.899613,ZorrO
27,44,ZrO__91Zr-16O__ZorrO__(91Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,91Zr-16O,(91Zr)(16O),<sup>91</sup>Zr<sup>16</sup>O,91zr16o,<sup>91</sup>Zr<sup>16</sup>O,106.900555,ZorrO
28,45,ZrO__92Zr-16O__ZorrO__(92Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,92Zr-16O,(92Zr)(16O),<sup>92</sup>Zr<sup>16</sup>O,92zr16o,<sup>92</sup>Zr<sup>16</sup>O,107.899950,ZorrO
29,46,ZrO__93Zr-16O__ZorrO__(93Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,93Zr-16O,(93Zr)(16O),<sup>93</sup>Zr<sup>16</sup>O,93zr16o,<sup>93</sup>Zr<sup>16</sup>O,108.901385,ZorrO
30,47,ZrO__94Zr-16O__ZorrO__(94Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,94Zr-16O,(94Zr)(16O),<sup>94</sup>Zr<sup>16</sup>O,94zr16o,<sup>94</sup>Zr<sup>16</sup>O,109.901227,ZorrO
31,48,ZrO__96Zr-16O__ZorrO__(96Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,96Zr-16O,(96Zr)(16O),<sup>96</sup>Zr<sup>16</sup>O,96zr16o,<sup>96</sup>Zr<sup>16</sup>O,111.903192,ZorrO

In [3]:
pieces_df.to_csv('~/ExoMolHR-web/res/exomolhr.csv', index=False, columns=pieces_colnames)

In [4]:
molecules_df = pieces_df[['molecule', 'molhtml', 'moltag', 'molname', 'molmass']].drop_duplicates().sort_values(by=['moltag'])
molecules_df['molid'] = molecules_df.reset_index().index+1
# molecules_df['molname'] = ['Aluminum monochloride', 'Aluminum hydride', 'Aluminum monoxide','Dicarbon', 'Acetylene', 
#                            'Calcium monohydride', 'Calcium monohydroxide', 'Cyano radical', 'Carbon dioxide', 'Formaldehyde ', 
#                            'Water', 'Hydrogen sulfide', 'Trihydrogen cation', 'Hydronium cation', 'Magnesium monohydride', 
#                            'Sodium oxide', 'Sodium hydroxide', 'Ammonia', 'Nitric oxide', 'Silicon nitride',
#                            'Silicon monoxide', 'Sulfur dioxide', 'Titanium oxide']
molecules_colnames = ['molid', 'molecule', 'molhtml', 'moltag', 'molname', 'molmass']
molecules_df = molecules_df[molecules_colnames]
molecules_df

,molid,molecule,molhtml,moltag,molname,molmass
2,1,AlCl,AlCl,alcl,Aluminum monochloride,62.431538
4,2,AlH,AlH,alh,Aluminum hydride,27.989538
17,3,AlO,AlO,alo,Aluminum monoxide,42.980538
19,4,C2,C<sub>2</sub>,c2,Dicarbon,24.022000
20,5,C2H2,C<sub>2</sub>H<sub>2</sub>,c2h2,Acetylene,26.038000
9,6,CaH,CaH,cah,Calcium monohydride,41.086000
0,7,CN,CN,cn,Cyano radical,26.018000
41,8,CO2,CO<sub>2</sub>,co2,Carbon dioxide,44.009000
47,9,H2CO,H<sub>2</sub>CO,h2co,Formaldehyde,30.026000
35,10,H2O,H<sub>2</sub>O,h2o,Water,18.015000
1,11,H2S,H<sub>2</sub>S,h2s,Hydrogen sulfide,34.076000
40,12,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000
36,13,H3O+,H<sub>3</sub>O<sup>+</sup>,h3o+,Hydronium cation,19.023000
46,14,LiOH,LiOH,lioh,Lithium hydroxide,23.947000
3,15,MgH,MgH,mgh,Magnesium monohydride,25.313000
6,16,NH,NH,nh,Imidogen,15.015000
38,17,NH3,NH<sub>3</sub>,nh3,Ammonia,17.031000
12,18,NO,NO,no,Nitric oxide,30.006000
21,19,SiN,SiN,sin,Silicon nitride,42.092000
32,20,SiO,SiO,sio,Silicon monoxide,44.084000
42,21,SO,SO,so,Sulfur monoxide,48.059000
37,22,SO2,SO<sub>2</sub>,so2,Sulfur dioxide,64.058000
25,23,TiO,TiO,tio,Titanium oxide,63.866000
43,24,YO,YO,yo,Yttrium monoxide,104.904840
26,25,ZrO,ZrO,zro,Zirconium oxide,107.223000

In [5]:
molecules_df.to_csv('~/ExoMolHR-web/res/molecules.csv', index=False, columns=molecules_colnames)

In [21]:
# isotopologues_df = pieces_df.loc[:, ['molecule', 'molhtml', 'molname', 
#                                      'isoslug', 'isoformula', 'isohtml', 'isotag', 'isomass', 
#                                      'dataset', 'filename']].drop_duplicates()
# isotopologues_df['id'] = isotopologues_df.reset_index().index+1
# isotopologues_colnames = ['id', 'molecule', 'molhtml', 'molname', 'isoslug', 'isoformula', 'isotag', 'isomass', 'dataset', 'filename']
# isotopologues_df = isotopologues_df[isotopologues_colnames]
# isotopologues_df.to_csv('~/ExoMolHR-web/res/isotopologues.csv', index=False, columns=isotopologues_colnames)
# isotopologues_df

,id,molecule,molhtml,molname,isoslug,isoformula,isotag,isomass,dataset,filename
2,1,AlCl,AlCl,Aluminum monochloride,27Al-35Cl,(27Al)(35Cl),27al35cl,61.950391,YNAT,AlCl__27Al-35Cl__YNAT__(27Al)(35Cl).csv
16,2,AlCl,AlCl,Aluminum monochloride,27Al-37Cl,(27Al)(37Cl),27al37cl,63.947441,YNAT,AlCl__27Al-37Cl__YNAT__(27Al)(37Cl).csv
4,3,AlH,AlH,Aluminum hydride,27Al-1H,(27Al)(1H),27al1h,27.989363,AloHa,AlH__27Al-1H__AloHa__(27Al)(1H).csv
8,4,AlH,AlH,Aluminum hydride,27Al-2H,(27Al)(2H),27al2h,28.995640,AloHa,AlH__27Al-2H__AloHa__(27Al)(2H).csv
19,5,AlO,AlO,Aluminum monoxide,26Al-16O,(26Al)(16O),26al16o,41.981806,ATP,AlO__26Al-16O__ATP__(26Al)(16O).csv
15,6,AlO,AlO,Aluminum monoxide,27Al-16O,(27Al)(16O),27al16o,42.976453,ATP,AlO__27Al-16O__ATP__(27Al)(16O).csv
18,7,AlO,AlO,Aluminum monoxide,27Al-17O,(27Al)(17O),27al17o,43.980670,ATP,AlO__27Al-17O__ATP__(27Al)(17O).csv
20,8,AlO,AlO,Aluminum monoxide,27Al-18O,(27Al)(18O),27al18o,44.980698,ATP,AlO__27Al-18O__ATP__(27Al)(18O).csv
21,9,C2,C<sub>2</sub>,Dicarbon,12C2,(12C)2,12c2,24.000000,8states,C2__12C2__8states__(12C)2.csv
22,10,C2H2,C<sub>2</sub>H<sub>2</sub>,Acetylene,12C2-1H2,(12C)2(1H)2,12c21h2,26.015650,aCeTY,C2H2__12C2-1H2__aCeTY__(12C)2(1H)2.csv
10,11,CaH,CaH,Calcium monohydride,40Ca-1H,(40Ca)(1H),40ca1h,40.970416,XAB,CaH__40Ca-1H__XAB__(40Ca)(1H).csv
0,12,CN,CN,Cyano radical,12C-14N,(12C)(14N),12c14n,26.003074,Trihybrid,CN__12C-14N__Trihybrid__(12C)(14N).csv
47,13,CO2,CO<sub>2</sub>,Carbon dioxide,12C-16O2,(12C)(16O)2,12c16o2,43.989829,UCL-4000,CO2__12C-16O2__UCL-4000__(12C)(16O)2.csv
53,14,H2CO,H<sub>2</sub>CO,Formaldehyde,1H2-12C-16O,(1H)2(12C)(16O),1h212c16o,30.010565,AYTY,H2CO__1H2-12C-16O__AYTY__(1H)2(12C)(16O).csv
41,15,H2O,H<sub>2</sub>O,Water,1H2-16O,(1H)2(16O),1h216o,18.010565,POKAZATEL,H2O__1H2-16O__POKAZATEL__(1H)2(16O).csv
1,16,H2S,H<sub>2</sub>S,Hydrogen sulfide,1H2-32S,(1H)2(32S),1h232s,33.987721,AYT2,H2S__1H2-32S__AYT2__(1H)2(32S).csv
46,17,H3+,H<sub>3</sub><sup>+</sup>,Trihydrogen cation,1H2-2H+,(1H)2(2H)+,1h22h+,4.029752,ST,H3_p__1H2-2H_p__ST__(1H)2(2H)+.csv
40,18,H3+,H<sub>3</sub><sup>+</sup>,Trihydrogen cation,1H3+,(1H)3+,1h3+,3.023475,MiZATeP,H3_p__1H3_p__MiZATeP__(1H)3+.csv
45,19,H3+,H<sub>3</sub><sup>+</sup>,Trihydrogen cation,2H2-1H+,(2H)2(1H)+,2h21h+,5.036029,MiZo,H3_p__2H2-1H_p__MiZo__(2H)2(1H)+.csv
17,20,H3+,H<sub>3</sub><sup>+</sup>,Trihydrogen cation,2H3+,(2H)3+,2h3+,6.042305,MiZo,H3_p__2H3_p__MiZo__(2H)3+.csv
42,21,H3O+,H<sub>3</sub>O<sup>+</sup>,Hydronium cation,1H3-16O+,(1H)3(16O)+,1h316o+,19.018390,eXeL,H3O_p__1H3-16O_p__eXeL__(1H)3(16O)+.csv
52,22,LiOH,LiOH,Lithium hydroxide,6Li-16O-1H,(6Li)(16O)(1H),6li16o1h,23.017863,OYT7,LiOH__6Li-16O-1H__OYT7__(6Li)(16O)(1H).csv
39,23,LiOH,LiOH,Lithium hydroxide,7Li-16O-1H,(7Li)(16O)(1H),7li16o1h,24.018743,OYT7,LiOH__7Li-16O-1H__OYT7__(7Li)(16O)(1H).csv
3,24,MgH,MgH,Magnesium monohydride,24Mg-1H,(24Mg)(1H),24mg1h,24.992867,XAB,MgH__24Mg-1H__XAB__(24Mg)(1H).csv
5,25,MgH,MgH,Magnesium monohydride,25Mg-1H,(25Mg)(1H),25mg1h,25.993662,XAB,MgH__25Mg-1H__XAB__(25Mg)(1H).csv
7,26,MgH,MgH,Magnesium monohydride,26Mg-1H,(26Mg)(1H),26mg1h,26.990418,XAB,MgH__26Mg-1H__XAB__(26Mg)(1H).csv
13,27,NaO,NaO,Sodium oxide,23Na-16O,(23Na)(16O),23na16o,38.984684,NaOUCMe,NaO__23Na-16O__NaOUCMe__(23Na)(16O).csv
6,28,NH,NH,Imidogen,14N-1H,(14N)(1H),14n1h,15.010899,kNigHt,NH__14N-1H__kNigHt__(14N)(1H).csv
12,29,NH,NH,Imidogen,14N-2H,(14N)(2H),14n2h,16.017176,kNigHt,NH__14N-2H__kNigHt__(14N)(2H).csv
9,30,NH,NH,Imidogen,15N-1H,(15N)(1H),15n1h,16.007934,kNigHt,NH__15N-1H__kNigHt__(15N)(1H).csv
11,31,NH,NH,Imidogen,15N-2H,(15N)(2H),15n2h,17.014211,kNigHt,NH__15N-2H__kNigHt__(15N)(2H).csv
44,32,NH3,NH<sub>3</sub>,Ammonia,14N-1H3,(14N)(1H)3,14n1h3,17.026549,CoYuTe,NH3__14N-1H3__CoYuTe__(14N)(1H)3.csv
14,33,NO,NO,Nitric oxide,14N-16O,(14N)(16O),14n16o,29.997989,XABC,NO__14N-16O__XABC__(14N)(16O).csv
23,34,SiN,SiN,Silicon nitride,28Si-14N,(28Si)(14N),28si14n,41.980001,SiNfull,SiN__28Si-14N__SiNfull__(28Si)(14N).csv
24,35,SiN,SiN,Silicon nitride,28Si-15N,(28Si)(15N),28si15n,42.977035,SiNfull,SiN__28Si-15N__SiNfull__(28Si)(15N).csv
25,36,SiN,SiN,Silicon nitride,29Si-14N,(29Si)(14N),29si14n,42.979569,SiNfull,SiN__29Si-14N__SiNfull__(29Si)(14N).csv
26,37,SiN,SiN,Silicon nitride,30Si-14N,(30Si)(14N),30si14n,43.976844,SiNfull,SiN__30Si-14N__SiNfull__(30Si)(14N).csv
38,38,SiO,SiO,Silicon monoxide,28Si-16O,(28Si)(16O),28si16o,43.971841,SiOUVenIR,SiO__28Si-16O__SiOUVenIR__(28Si)(16O).csv
48,39,SO,SO,Sulfur monoxide,32S-16O,(32S)(16O),32s16o,47.966986,SOLIS,SO__32S-16O__SOLIS__(32S)(16O).csv
43,40,SO2,SO<sub>2</sub>,Sulfur dioxide,32S-16O2,(32S)(16O)2,32s16o2,63.961900,ExoAmes,SO2__32S-16O2__ExoAmes__(32S)(16O)2.csv
27,41,TiO,TiO,Titanium oxide,46Ti-16O,(46Ti)(16O),46ti16o,61.947541,Toto,TiO__46Ti-16O__Toto__(46Ti)(16O).csv
28,42,TiO,TiO,Titanium oxide,47Ti-16O,(47Ti)(16O),47ti16o,62.946672,Toto,TiO__47Ti-16O__Toto__(47Ti)(16O).csv
29,43,TiO,TiO,Titanium oxide,48Ti-16O,(48Ti)(16O),48ti16o,63.942856,Toto,TiO__48Ti-16O__Toto__(48Ti)(16O).csv
30,44,TiO,TiO,Titanium oxide,49Ti-16O,(49Ti)(16O),49ti16o,64.942779,Toto,TiO__49Ti-16O__Toto__(49Ti)(16O).csv
31,45,TiO,TiO,Titanium oxide,50Ti-16O,(50Ti)(16O),50ti16o,65.939700,Toto,TiO__50Ti-16O__Toto__(50Ti)(16O).csv
49,46,YO,YO,Yttrium monoxide,89Y-16O,(89Y)(16O),89y16o,104.900756,BRYTS,YO__89Y-16O__BRYTS__(89Y)(16O).csv
50,47,YO,YO,Yttrium monoxide,89Y-17O,(89Y)(17O),89y17o,105.904973,BRYTS,YO__89Y-17O__BRYTS__(89Y)(17O).csv
51,48,YO,YO,Yttrium monoxide,89Y-18O,(89Y)(18O),89y18o,106.905001,BRYTS,YO__89Y-18O__BRYTS__(89Y)(18O).csv
32,49,ZrO,ZrO,Zirconium oxide,90Zr-16O,(90Zr)(16O),90zr16o,105.899613,ZorrO,ZrO__90Zr-16O__ZorrO__(90Zr)(16O).csv
33,50,ZrO,ZrO,Zirconium oxide,91Zr-16O,(91Zr)(16O),91zr16o,106.900555,ZorrO,ZrO__91Zr-16O__ZorrO__(91Zr)(16O).csv
34,51,ZrO,ZrO,Zirconium oxide,92Zr-16O,(92Zr)(16O),92zr16o,107.899950,ZorrO,ZrO__92Zr-16O__ZorrO__(92Zr)(16O).csv
35,52,ZrO,ZrO,Zirconium oxide,93Zr-16O,(93Zr)(16O),93zr16o,108.901385,ZorrO,ZrO__93Zr-16O__ZorrO__(93Zr)(16O).csv
36,53,ZrO,ZrO,Zirconium oxide,94Zr-16O,(94Zr)(16O),94zr16o,109.901227,ZorrO,ZrO__94Zr-16O__ZorrO__(94Zr)(16O).csv
37,54,ZrO,ZrO,Zirconium oxide,96Zr-16O,(96Zr)(16O),96zr16o,111.903192,ZorrO,ZrO__96Zr-16O__ZorrO__(96Zr)(16O).csv

In [16]:
molecule = 'CN'
isotopologues_df = pieces_df[pieces_df['molecule'].isin([molecule])]
isotopologues_df = isotopologues_df[['molecule', 'molhtml', 'molname', 
                                     'isoslug', 'isoformula', 'isohtml', 'isotag', 'isomass']].drop_duplicates()
isotopologues_df['id'] = isotopologues_df.reset_index().index+1
isotopologues_df

,molecule,molhtml,molname,isoslug,isoformula,isohtml,isohtml,isotag,isomass,id
0,CN,CN,Cyano radical,12C-14N,(12C)(14N),<sup>12</sup>C<sup>14</sup>N,<sup>12</sup>C<sup>14</sup>N,12c14n,26.003074,1

In [17]:
# molecule = 'CN'
# isotopologues_df = pd.read_csv('~/ExoMolHR-web/res/pieces.csv', header=0)
# isotopologues_df = isotopologues_df[isotopologues_df['molecule'].isin([molecule])].drop(columns=['id', 'dataset']).drop_duplicates()
# isotopologues_df['id'] = isotopologues_df.reset_index().index+1
# isotopologues_df = isotopologues_df[['id', 'molecule', 'molformula', 'molname', 'isoslug', 'isoformula', 'isotag', 'isomass']]
# isotopologues_df

In [18]:
molecule = 'CN'
isotopologue = '12C-14N'
datasets_df = pieces_df[pieces_df[['molecule', 'isoslug']].isin([molecule, isotopologue]).all(axis=1)]
datasets_df = datasets_df[['molecule', 'molhtml', 'molname', 
                           'isoslug', 'isoformula', 'isohtml', 'isotag', 'isomass',
                           'dataset', 'filename']].drop_duplicates()
datasets_df['id'] = datasets_df.reset_index().index+1
datasets_df

,molecule,molhtml,molname,isoslug,isoformula,isohtml,isohtml,isotag,isomass,dataset,filename,id
0,CN,CN,Cyano radical,12C-14N,(12C)(14N),<sup>12</sup>C<sup>14</sup>N,<sup>12</sup>C<sup>14</sup>N,12c14n,26.003074,Trihybrid,CN__12C-14N__Trihybrid__(12C)(14N).csv,1

In [19]:
# molecule = 'CN'
# isotopologue = '12C-14N'
# dataset_df = pd.read_csv('~/ExoMolHR-web/res/isotopologues.csv', header=0)
# dataset_df = dataset_df[dataset_df[['molecule', 'isoslug']].isin([molecule, isotopologue]).all(axis=1)]
# dataset_df['id'] = dataset_df.reset_index().index+1
# dataset_df

In [20]:
list(datasets_df[datasets_df['isoslug'].isin([isotopologue])]['isoformula'])[0]

'(12C)(14N)'